name: Hello World
on: 
   push:
     branches: [main]
     #paths-ignore:
     #   - ".github/workflows/*"   #สั่งให้ยกเว้น Patch นี้
   pull_request:
      branches: [main]
   repository_dispatch:   #สั่งให้ทำงานผ่าน การเรียก API
      types: [on-demand-test]
jobs:
    echo-vars:
      runs-on: ubuntu-latest
      steps:
       - name : Echo Github Variable
         env:
            APP_VERSION : "2.2.2"
            RUNNER_CONTEX: ${{toJson(runner)}}
         run: 
             echo "The Database password is ${{secrets.DB_PASSWORD}}"
            echo "This job event name by ${{github.event.name}}"
            echo "This job repository by ${{github.repository}}"
            #echo "This job trigger by ${{github.ref_name}}"
            #echo "This is a ${{env.APP_NAME}} Version ${{env.APP_VERSION}}"
            #echo "$RUNNER_CONTEX"
           # echo "The Database password is ${{secrets.DB_PASSWORD}}"
    hello-job :
       if: ${{github.event_name != 'repository_dispatch'}}
       runs-on: ubuntu-latest  # เรียกใช้ OS
       steps:
          - name: run a one line script
            run: echo Hello World Github Actions
       #   - name: retrieve client payload
       #     run: echo "client send status :${{github.event.client_payload.status}}"
    Seccond-job:  #เพิ่ม job ที่ 2
       if: ${{ github.event_name == 'on-demand-test' }}  
       runs-on: windows-latest
       needs: hello-job  #สั่ง่ให้ทำงานแบบ sequent
       steps:
         - run: echo "this Job is runing on ${{runner.os}}"
         
