name: My Workflow
 
on:
  push:
    branches: [main]
     paths-ignore:
       - '.github/workflows/*'
    pull_request:
      branches: [main]
 
    repository_dispatch:
      types: ["on-demand-test"]
 
jobs:
  myJob:
    runs-on: ubuntu-latest
    steps:
       - name: Run a one-line script
         run: echo Hello, world
 
       - name: Retrieve client payload
         env:
          PAYLOAD_STATUS: ${{ github.event.client_payload.status }}
         run: echo "Client payload $PAYLOAD_STATUS"
  secondJob:
    runs-on: windows-latest
    needs: myJob
    steps:
       - name: Run a multi-line script
         run: |
           echo Add other actions to build ${{ runner.os }} project.,
           echo test, and deploy your project.
